<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-AppHostSetupWorker-d5b1f9c1-4adc-44b2-8013-4840d0ae1082</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" Version="13.5.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProjectHub.Data\ProjectHub.Data.csproj" />
    <ProjectReference Include="..\ProjectHub.ServiceDefaults\ProjectHub.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
